### PR TITLE
Fix variant page crashing when multiple product images

### PR DESCRIPTION
**Pull request by devenvyas**
I want to merge this change because it fixes an issue where dashboard crashes on navigating to variant page if the product has more than 1 image.

Fixes issues - #1962 

**PR intended to be tested with API branch:** 3.1.8

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

### CODE REVIEW

**Comment by devenvyas** [comment]
@Kjaroszew is there something needed to get the review process started? let me know!

**Review by Kjaroszew — APPROVED** [review]
Tested steps form https://github.com/saleor/saleor-dashboard/issues/1962 and it seems that everything is working as intended.

**Comment by RyanTamulevicz** [comment]
@devenvyas lifesaving fix. thank you!

**Comment by dominik-zeglen** [comment]
Hi, I'd do it myself but I don't have access - could you rebase your branch?

**Comment by andrzejewsky** [comment]
Flow up to the previous message - could you rebase @devenvyas ?

**Pull request closed without merging**
