### PR TITLE
Use schema-ast plugin to generate the graphql schema

### PR DESCRIPTION
**Pull request by abumalick**
I want to merge this change because...

It is simplifying the graphql schema generation / less code for you to maintain.

I tested my changes like this:
- I ran `fetch-schema` before my changes
- stage the changes made to `schema.graphql`
- make my changes
- remove `schema.graphql`
- run again `fetch-schema`

After following this process, there was not a single change between the newly generated file and the one staged.

**PR intended to be tested with API branch:** main

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [x] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://demo.saleor.io/graphql/

### Do you want to run more stable tests?
To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants

CONTAINERS=1

### CODE REVIEW

**Comment by abumalick** [comment]
any feedback?

**Review by krzysztofzuraw — APPROVED** [review]

**Review by Droniu — DISMISSED** [review]

**Comment by andrzejewsky** [comment]
@poulch i think it will make a conflict with your flags implementation as you have changed these scripts as well

**Review by andrzejewsky — APPROVED** [review]

**Comment by abumalick** [comment]
The PR has 3 approvals and didn't get merged. If I update the branch are you going to merge it?

**Comment by krzysztofzuraw** [comment]
Yes - @abumalick please fix conflicts and we are going to merge this PR 😄

**Comment by abumalick** [comment]
All right, I just tested again, it is still working as expected @krzysztofzuraw 

```bash
API_URI=https://demo.saleor.io/graphql/ npm run fetch-schema              
```

**Review by krzysztofzuraw — APPROVED** [review]

**Review by poulch — APPROVED** [review]

**Comment by krzysztofzuraw** [comment]
Thank you @abumalick for your contribution 🎉

**Comment by abumalick** [comment]
You are welcome

**Pull request merged**
