### PR TITLE
Fix flaky test for creating variant

### PR DESCRIPTION
**Pull request by karola312**
I want to merge this change because I fixed flaky test for creating variant

**PR intended to be tested with API branch:** 

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-6703 [FIX] should be able to create several variants visible for the customers.](https://app.clickup.com/t/2549495/SALEOR-6703)

**Review by michalina-graczyk — APPROVED** [review]

**Comment by karola312** [comment]
@Kjaroszew when testing please run in in loop with repeat 20.

**Review by witoszekdev — APPROVED** [review]

**Review by Kjaroszew — CHANGES_REQUESTED** [review]
I performed as you asked but described error still occur. Additionally TC: 2901 started to fail around 2 times of 20

**Review by Kjaroszew — APPROVED** [review]
Tested and everything seems to be working

**Pull request merged**
