### PR TITLE
Saleor 7517 Fixes not being able to update site settings

### LINKED ISSUE #2039: Unable to save Store Information due to GraphQLError
### What I'm trying to achieve
I'm trying to deploy (and run locally) a production-ready `saleor-dashboard`.

### Steps to reproduce the problem
1. Setup tag `3.3.1` of `saleor-dashboard` and tag `3.3.2` of `saleor`
2. Setup nginx serving results of `npm run build`
3. Navigate to `/site-settings` -> fill in `Store Information` -> hit `Save`
4. See error in browser console (no error popup or validation errors are visible).

### What I expected to happen
Store address is saved successfully

### Screenshots

2022-05-11-162328_1365x1288_scrot

### Http request and response from inspector

Request:
```
{
  "operationName":"ShopSettingsUpdate",
  "variables": {
  "addressInput":{
    "city":"Testville",
    "companyName":"Company  B.V.",
    "country":"NL",
    "countryArea":"",
    "phone":"",
    "postalCode":"1000AA",
    "streetAddress1":"Teststreet 33",
    "streetAddress2":""
  },
  "shopSettingsInput":{
    "description":"",
    "reserveStockDurationAnonymousUser":null,
    "reserveStockDurationAuthenticatedUser":null
  },
  "isCloudInstance":false
},
"query":"mutation ShopSettingsUpdate(
  $shopSettingsInput: ShopSettingsInput!,
  $addressInput: AddressInput,
  $isCloudInstance: Boolean!) {
  shopSettingsUpdate(input: $shopSettingsInput) {
    errors {
      ...ShopError
      __typename
    }
    shop {
      ...Shop
      __typename
    }
    __typename
  }
  shopAddressUpdate(input: $addressInput) {
    errors {
      ...ShopError
      __typename
    }
    shop {
      companyAddress {
        ...Address
        __typename
      }
      __typename
    }
    __typename
  }
}

fragment ShopError on ShopError {
  code
  field
  message
  __typename
}

fragment Shop on Shop {
  companyAddress {
    ...Address
    __typename
  }
  countries {
    code
    country
    __typename
  }
  customerSetPasswordUrl
  defaultMailSenderAddress
  defaultMailSenderName
  description
  domain {
    host
    __typename
  }
  name
  reserveStockDurationAnonymousUser
  reserveStockDurationAuthenticatedUser
  limitQuantityPerCheckout
  __typename
}

fragment Address on Address {
  city
  cityArea
  companyName
  country {
    __typename
    code
    country
  }
  countryArea
  firstName
  id
  lastName
  phone
  postalCode
  streetAddress1
  streetAddress2
  __typename
}"}
```

Response:
```
{"errors": [{"message": "Variable \"$isCloudInstance\" is never used in operation \"ShopSettingsUpdate\".", "locations": [{"line": 1, "column": 98}], "extensions": {"exception": {"code": "GraphQLError"}}}], "extensions": {"cost": {"requestedQueryCost": 0, "maximumAvailable": 50000}}}
```

### Console output

```
// insert console output here 
Variable "$isCloudInstance" is never used in operation "ShopSettingsUpdate".
```

**System information**

Saleor version:
- [ ] dev (current main)
- [x] 3.3.1
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system: 
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other 

Browser:
- [x] Firefox
- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

### PR DESCRIPTION
**Pull request by RyanTamulevicz**
I want to merge this change because...
Fixes being able to change your site settings in the dashboard. I am unsure how this interacts with your Cloud instance and changing those settings post this update. This fixes local hosts though.

fixes #2039
**PR intended to be tested with API branch:** 

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://marketplace-gray.vercel.app/

### CODE REVIEW

**Comment by eCzerniak** [comment]
@TobKed we have test for it [here](https://github.com/saleor/saleor-dashboard/blob/main/cypress/e2e/configuration/siteSettings.js) and after merge we will include this test in our test suite - now it is disabled.

**Comment by RyanTamulevicz** [comment]
> 

I will say I have almost completed building my store in dashboard v3.5.2 core v3.5.4 with this fix implemented as far as testing other features goes. Only thing I need to address is refunds not working, but I do not believe it is due to this fix at all and probably an Authorize.net change if I were to guess.

**Review by eCzerniak — APPROVED** [review]

**Review by Droniu — APPROVED** [review]

**Comment by timuric** [comment]
@RyanTamulevicz thanks for the contribution! Have you considered open sourcing authorize.net implementation? This would make it easier to provide with the support and accept contributions from other members of the community

**Comment by RyanTamulevicz** [comment]
> @RyanTamulevicz thanks for the contribution! Have you considered open sourcing authorize.net implementation? This would make it easier to provide with the support and accept contributions from other members of the community

@timuric I have not written it in the new Saleor Checkout format. It is a bit further down in my plans as I have it in a working state, but if someone else has not started work on it, I probably will. That error I was getting was just a one off from what I can see from a few more tests.

**Review by dominik-zeglen — APPROVED** [review]

**Pull request merged**
