### PR TITLE
Gift Card List item number change doesn't refetch fix

### PR DESCRIPTION
**Pull request by Cloud11PL**
I want to merge this change because I want to fix gift card list not refetching on item number change. 

**PR intended to be tested with API branch:** 

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://feature-gift-cards-post-mvp.api.saleor.rocks/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-5014 GiftCard list - pagination is not automatically refreshed.](https://app.clickup.com/t/2549495/SALEOR-5014)

**Review by orzechdev — APPROVED** [review]

**Review by Droniu — APPROVED** [review]

**Comment by Cloud11PL** [comment]
@Droniu Can you QA test it? https://saleor-5014-gift-card-list-item-number-change-doesnt-refresh.dashboard.saleor.rocks/gift-cards/

**Review by Droniu — CHANGES_REQUESTED** [review]
QA fail
When number of items is changed to e. g. 30 on the second page, the first page still has initial amount of items. Expected behaviour is to refresh the whole list (reset back to page 1, with new amount of items per page set) as it is in all other list views in the dashboard.

We have a custom hook for that already, look for `usePaginationReset`.

**Review by Droniu — APPROVED** [review]
✅ QA Pass

**Pull request merged**
