### PR TITLE
Demo banner

### PR DESCRIPTION
**Pull request by timuric**
I want to merge this change because...
Banner redesign to avoid shifting layout of the dashboard.

Behavior:
• Click hide
• Mouse over or tap on mobile to uncover

**PR intended to be tested with API branch:** 

### Screenshots

image

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
APPS_MARKETPLACE_API_URI=https://apps.staging.saleor.io/api/v2/saleor-apps
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?

To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=1

### CODE REVIEW

**Review by andrzejewsky — APPROVED** [review]

**Review by poulch — DISMISSED** [review]

**Review by Droniu — APPROVED** [review]

**Comment by wojteknowacki** [comment]
@timuric Does old banner is gone and drawer replaces it?

**Comment by timuric** [comment]
> @timuric Does old banner is gone and drawer replaces it?

Yes

**Comment by wojteknowacki** [comment]
1. Should it be possible to open it on every view? I guess yes but need confirmation.
2.  How should it look in the dark theme? A Mock/Screenshot would be great to compare browsers
3.  After you click on the link in the new banner should it open a new tab with the proper URL or load it in the current tab - or stays as it was?
4. When the drawer is open - hiding it is only possible by clicking the hide button or clicking outside should hide it also?
5. Buttons in the drawer should have a hover effect?
6. Button should have a click effect?

**Comment by timuric** [comment]
> 1. Should it be possible to open it on every view? I guess yes but need confirmation. (now it is visible also on login page and the old banner was not)
> 2. How should it look in the dark theme? A Mock/Screenshot would be great to compare browsers
> 3. After you click on the link in the new banner should it open a new tab with the proper URL or load it in the current tab - or stays as it was?
> 4. When the drawer is open - hiding it is only possible by clicking the hide button or clicking outside should hide it also?
> 5. Buttons in the drawer should have a hover effect?
> 6. Button should have a click effect?

1. I think it is relevant on all screens
2. The idea behind it being black is to stand out from the theme, so it is noticble
3. All links should open in new tab
4. This is correct, it should always be visible unless you want to hide it explicitly
5,6 yes, will add

**Comment by wojteknowacki** [comment]
@timuric Friendly reminder about z-index

**Review by wojteknowacki — APPROVED** [review]

**Review by andrzejewsky — APPROVED** [review]

**Pull request merged**
