### PR TITLE
Fix test for creating free shipping voucher

### PR DESCRIPTION
**Pull request by karola312**
I want to merge this change because...

**PR intended to be tested with API branch:** 

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://apps.saleor.io
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?
To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [x] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=1

### CODE REVIEW

**Review by michalina-graczyk — CHANGES_REQUESTED** [review]
Please rename from textes to taxes

**Comment by szczecha** [comment]
The change looks fine. I checked your PR on v39 env, and this test TC: SALEOR_1903 still fails for the reason:
Screenshot 2023-01-05 at 08 33 12

If instead of using the default channel test creates a new channel before() it works.

**Review by szczecha — COMMENTED** [review]
We can try here to update product and shipping tax classes like in orders https://github.com/saleor/saleor-dashboard/pull/2950

**Comment by karola312** [comment]
just disable taxes for default channel. @szczecha will it be ok? In the future we can have a different channel for tests for taxes

**Comment by szczecha** [comment]
> just disable taxes for default channel. @szczecha will it be ok? In the future we can have a different channel for tests for taxes

OK, here we check only if the voucher is applicable to the checkout.

**Review by michalina-graczyk — APPROVED** [review]

**Review by szczecha — APPROVED** [review]

**Review by NyanKiyoshi — APPROVED** [review]
CI: LGTM

**Pull request merged**
