### PR TITLE
Fix failing tests

### PR DESCRIPTION
**Pull request by karola312**
I want to merge this change because I fixed failing tests

**PR intended to be tested with API branch:** 

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://stable.staging.saleor.cloud/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-5606 Fix failing tests](https://app.clickup.com/t/2549495/SALEOR-5606)

**Review by eCzerniak — CHANGES_REQUESTED** [review]
I had many problems with those tests. I send to you direct message.

**Review by eCzerniak — APPROVED** [review]

**Comment by bmigirl** [comment]
Tests are still failling

**Comment by karola312** [comment]
PurchaseWithProductTypes, WeightRecalculate and SiteSettings - tests are failing because of existing bugs, so that is correct

**Review by bmigirl — APPROVED** [review]

**Pull request merged**
