### PR TITLE
Disable checkbox for products that are not available in selected channels

### PR DESCRIPTION
**Pull request by Cloud11PL**
## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [ ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

CleanShot 2024-05-07 at 12 05 04

## Have you written tests?
- [ ] Yes!
- [ ] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

### CODE REVIEW

**Review by poulch — COMMENTED** [review]
Check this PR https://github.com/saleor/saleor-dashboard/pull/4826, you could add your solution to my branch

**Comment by Cloud11PL** [comment]
@poulch this branch will be merged to the one you mentioned 😄

**Review by yellowee — APPROVED** [review]

**Review by poulch — COMMENTED** [review]
shouldn't you add text below each row like I did? 
`Product unavailable in shipping method channels`

**Review by andrzejewsky — APPROVED** [review]

**Review by andrzejewsky — CHANGES_REQUESTED** [review]
Hey @Cloud11PL please review @poulch pull request because seems like he did something very similar or even exact as you here. While code can be different, we should keep the same consistency between those UI

**Pull request merged**
