### PR TITLE
Update ProductVariantName components "name" form field into "variantName"

### PR DESCRIPTION
**Pull request by ilkaykisayol**
Note: This is a 3.9 port of https://github.com/saleor/saleor-dashboard/pull/2903

I want to merge this change because, it fixes variant name changes when entering value in the variant attributes and also update variantName form value when sku is changed
Fixes https://github.com/saleor/saleor-dashboard/issues/2831

**PR intended to be tested with API branch:** 

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://apps.saleor.io
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?
To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=1

### CODE REVIEW

**Comment by ogunheper** [comment]
Hi @poulch ,

This is a port of #2903 to 3.9

We would appreciate it if we can have this in the next 3.9.8 release.

Best regards and thank you,
Ogün

**Comment by poulch** [comment]
Hi @ogunheper.
Thanks for your contribution to the project.
Your pull request was merged and will be released in version 3.9.8 soon, you don't have to prepare a separate pull request to the release branch.

**Comment by ogunheper** [comment]
Hi @poulch ,

Thanks for the info. I just want to clarify that our previous PR was towards main branch, not 3.9. Will it still be included in 3.9.8 release?

Best and thank you,
Ogün

**Comment by poulch** [comment]
@ogunheper yes it will be, don't worry. We prepare releases manually.

**Comment by ogunheper** [comment]
Thank you very much @poulch. I'm closing this now.

cc: @ilkaykisayol

**Pull request closed without merging**
