### PR TITLE
Always run critical - test PR

### PR DESCRIPTION
**Pull request by karola312**
I want to merge this change because its test pr to https://github.com/saleor/saleor-dashboard/pull/1579

**PR intended to be tested with API branch:** 

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-4042 Always run critical tests in CI](https://app.clickup.com/t/2549495/SALEOR-4042)

**Review by jwm0 — CHANGES_REQUESTED** [review]
It looks like the config change works, however the test fails. Is it a flaky test?

**Comment by karola312** [comment]
@jwm0 No, tests is ok, it fails is creating variants. When test is creating variants, test warehouse to assign is not displayed in variant creator. There is a bug for it - https://app.clickup.com/t/2549495/SALEOR-4896

**Review by jwm0 — COMMENTED** [review]
Re-request me for review when tests pass

**Review by jwm0 — APPROVED** [review]

**Pull request merged**
