### PR TITLE
Removing collection fix

### PR DESCRIPTION
**Pull request by Cloud11PL**
I want to merge this change because it fixes Warehouse and Collection multi autocomplete inputs that have choices selected not found in fetched list.

3.1 PR: https://github.com/saleor/saleor-dashboard/pull/1764

**PR intended to be tested with API branch:** 

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://stable.staging.saleor.cloud/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-5627 Removing Collection from the product page](https://app.clickup.com/t/2549495/SALEOR-5627)

**Review by dominik-zeglen — COMMENTED** [review]
I'm wondering if having this inside multiAutocompleteSelectFieldHandler would be an improvement to this or not

**Comment by Cloud11PL** [comment]
@dominik-zeglen I'm not sure, I would rather keep it separately as of now.

**Comment by dominik-zeglen** [comment]
Why though? It's not like it can be used separately, and it will be quite easy to omit this in future implementations of the widget 🤷‍♂️

**Review by bmigirl — APPROVED** [review]

**Comment by Cloud11PL** [comment]
@dominik-zeglen You're right. I was worried that the handler is used differently (choice handling) in other places but it seems to be fine.

**Review by dominik-zeglen — APPROVED** [review]

**Pull request merged**
