### PR TITLE
View all orders of anonymous customer

### LINKED ISSUE #3753: Add "view all orders" to anonymous customers
Customer support often needs to see all orders of a customer, in case of registered user Order page links to the profile of customer where all orders can be seen. For anonymous users support person needs to copy the email from Order page, navigate to orders list, filter by email. It would be very convenient to have a link instead

image

### PR DESCRIPTION
**Pull request by iammatthi**
closes #3753 

On the order page there is now a link under the email to see all orders of an anonymous customer.

### Screenshots
Order page (before):
image

Order page (after):
image

View Orders page:
image

### Pull Request Checklist

1. [X] This code contains UI changes
2. [X] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `data-test-id` are added for new elements
4. [ ] The changes are tested in Chrome/Firefox/Safari browsers and in light/dark mode
5. [X] Your code works with the latest stable version of the core
6. [ ] I added changesets and [read good practices](/.changeset/README.md)

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
APPS_MARKETPLACE_API_URI=https://apps.staging.saleor.io/api/v2/saleor-apps

### Do you want to run more stable tests?

To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=1

### CODE REVIEW

**Review by andrzejewsky — APPROVED** [review]

**Comment by andrzejewsky** [comment]
Thanks for the PR! is it ready for review? I've noticed you have changed it to draft again?

**Comment by iammatthi** [comment]
> Thanks for the PR! is it ready for review? I've noticed you have changed it to draft again?

I have noticed that in the View Orders page screenshot there is also another customer (Holly Acosta). I need to check why it happened.

**Comment by iammatthi** [comment]
By my side there seems to be a bug with the filter of orders by customer email. If I filter by customer email, for example maria.martinez@example.com (url: http://localhost:9000/orders?asc=false&sort=number&customer=maria.martinez%40example.com), here is what I get: 
image

Note that Holly Acosta and Alicia Perkins are registered customer.

Can you check whether for you is working?

**Review by krzysztofzuraw — DISMISSED** [review]

**Comment by andrzejewsky** [comment]
@iammatthi we are aware of this. It's about the way of how the API sorts the results vs what we display as "customer" - sometimes there is no email while we display eg first name/last name

**Comment by iammatthi** [comment]
All right. This PR's feature should then work as soon as the filter by email works.

**Comment by krzysztofzuraw** [comment]
@iammatthi it seems that there are two issues with your PR that were caught by our CI:
1) `tsc-and-linters` - it seems that there is a file not formatted by a prettier 
2) `translation-messages` - run `npm run extract-messages` and commit the result

**Review by krzysztofzuraw — APPROVED** [review]

**Review by andrzejewsky — APPROVED** [review]
Looks good! Thanks a lot! CC: @timuric would you have a look?

**Comment by timuric** [comment]
@iammatthi looking great! Thank you!

**Pull request merged**
