### PR TITLE
wrongly named file

### PR DESCRIPTION
**Pull request by GabrielZacchi**
The translation into Brazilian Portuguese does not work due to the wrong file name, which is pt_BR.json, when it should be pt-BR.json.

### CODE REVIEW

**Review by poulch — DISMISSED** [review]
Hi, thanks for your contribution, indeed translations don't work with underscore.
Could you run `npm run change:add`, select `patch` and provide a description?

**Comment by GabrielZacchi** [comment]
@poulch  done

**Review by poulch — APPROVED** [review]

**Comment by GabrielZacchi** [comment]
How long does it take to upload the docker image with this fix?

**Comment by poulch** [comment]
@GabrielZacchi pleas accept 'Contributor License Agreement' because we can not merge without it

**Comment by GabrielZacchi** [comment]
@poulch Done

**Pull request merged**
