### PR TITLE
Voucher codes with API

### PR DESCRIPTION
**Pull request by poulch**
closes https://github.com/saleor/saleor-dashboard/issues/4182

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `data-test-id` are added for new elements
4. [ ] The changes are tested in Chrome/Firefox/Safari browsers and in light/dark mode
5. [ ] Your code works with the latest stable version of the core
6. [ ] I added changesets file (instructions in [contribution guide](https://github.com/saleor/saleor-dashboard/blob/main/.github/CONTRIBUTING.md)

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
APPS_MARKETPLACE_API_URI=https://apps.staging.saleor.io/api/v2/saleor-apps

### Do you want to run more stable tests?

To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] app
3. [ ] attribute
4. [ ] category
5. [ ] collection
6. [ ] customer
7. [ ] giftCard
8. [ ] homePage
9. [ ] login
10. [ ] menuNavigation
11. [ ] navigation
12. [ ] orders
13. [ ] pages
14. [ ] payments
15. [ ] permissions
16. [ ] plugins
17. [ ] productType
18. [ ] products
19. [ ] sales
20. [ ] shipping
21. [ ] translations
22. [ ] variants
23. [ ] vouchers

CONTAINERS=6

### CODE REVIEW

**Review by Droniu — APPROVED** [review]
LGTM

**Comment by wojteknowacki** [comment]
When added autogenerated code and moving back to vouchers list view user is not prompted confirmation dialog 

https://github.com/saleor/saleor-dashboard/assets/124166231/b76b93e2-c8a6-4a95-8fc4-d3601a8e1dec

**Comment by wojteknowacki** [comment]
Saving voucher when no codes provided - alert message text could be more descriptive like "please provide at least one code" 
Zrzut ekranu 2023-11-6 o 12 59 26

**Comment by wojteknowacki** [comment]
Confirm button should be disabled until quantity input value is provided
Zrzut ekranu 2023-11-6 o 13 05 39

**Comment by wojteknowacki** [comment]
When the user provides discount value and then changes available  channels - discount value is lost
https://github.com/saleor/saleor-dashboard/assets/124166231/5bd19f61-3f62-4543-b604-1d2169793602

**Comment by wojteknowacki** [comment]
User can add the same code twice if statuses are different

https://github.com/saleor/saleor-dashboard/assets/124166231/15508e8c-53a3-48a0-b09e-35b593173667

**Comment by wojteknowacki** [comment]
When pagination reaches last page, the size of the grid should not change 
https://github.com/saleor/saleor-dashboard/assets/124166231/a9aa37cc-e9b5-42ec-96e1-faa8f65f84fa

**Comment by wojteknowacki** [comment]
Should we keep Uasge limit in right side section?
Zrzut ekranu 2023-11-6 o 22 03 13

**Comment by wojteknowacki** [comment]
Inform user it is not possible to delete active codes

**Comment by wojteknowacki** [comment]
Error state remains after closing the add code modal. The user adds code XYZ which is already present in voucher codes and closes the modal. Opes modal again - error state still present
Zrzut ekranu 2023-11-7 o 12 27 31

**Review by wojteknowacki — APPROVED** [review]

**Review by wojteknowacki — APPROVED** [review]

**Review by Droniu — APPROVED** [review]

**Pull request merged**
