### PR TITLE
Allow to copy and go to product details on order details datagrid

### PR DESCRIPTION
**Pull request by poulch**
closes https://github.com/saleor/saleor-dashboard/issues/3740
### Screenshots

| Before | After |
| ------- | ------- |
| Screenshot 2023-06-09 at 12 41 25 |  Screenshot 2023-06-09 at 12 41 45 |

| Before | After |
| ------- | ------- |
| Screenshot 2023-06-12 at 14 41 24 |   Screenshot 2023-06-12 at 14 41 02 |
  
### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `data-test-id` are added for new elements
4. [ ] The changes are tested in Chrome/Firefox/Safari browsers and in light/dark mode
5. [ ] Your code works with the latest stable version of the core

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
APPS_MARKETPLACE_API_URI=https://apps.staging.saleor.io/api/v2/saleor-apps

### Do you want to run more stable tests?

To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [x] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=6

### CODE REVIEW

**Review by krzysztofzuraw — APPROVED** [review]

**Review by krzysztofzuraw — DISMISSED** [review]

**Review by andrzejewsky — CHANGES_REQUESTED** [review]

**Review by andrzejewsky — APPROVED** [review]

**Comment by wojteknowacki** [comment]
Not sure how the user should know there is such a feature as copy-pasting if we do not show copy action when right mouse click

**Comment by wojteknowacki** [comment]
User copies cells with strings and numbers and paste to cells which accepts only numbers

https://github.com/saleor/saleor-dashboard/assets/124166231/ef56ab57-bd79-49c5-97bc-865da7f23101

**Comment by wojteknowacki** [comment]
The user copies 4 cells from different rows but when selecting pasting place selects only one cell - then is pasting all copied rows - not sure if this is how it should behave - might change rows that should not be changed. Also request amount and banners displayed exceed changed rows
https://github.com/saleor/saleor-dashboard/assets/124166231/73e6f493-8978-4873-b253-afc0297e3551

**Comment by wojteknowacki** [comment]
"Hand" pointer should be visible only on clickable elements - now it is visible between icons "go-to product details" and clicking makes no effect

https://github.com/saleor/saleor-dashboard/assets/124166231/2e238f71-cbec-4ff6-ba0d-3354135686c0

**Review by wojteknowacki — APPROVED** [review]

**Review by andrzejewsky — APPROVED** [review]

**Pull request merged**
