### PR TITLE
Fix variant selection attribute

### PR DESCRIPTION
**Pull request by karola312**
I want to merge this change because I removed test for adding date attribute as variant selection

**PR intended to be tested with API branch:** 

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-6247 [Fix] Create variant with variant selection attribute](https://app.clickup.com/t/2549495/SALEOR-6247)

**Review by eCzerniak — APPROVED** [review]
Please remove one not used import which I mention and it is OK.

**Review by bmigirl — APPROVED** [review]

**Review by Kjaroszew — COMMENTED** [review]
code seems to be ok but during execution serval errors occurred
image

**Review by Kjaroszew — APPROVED** [review]
OK

**Pull request merged**
