### PR TITLE
Always run critical tests

### PR DESCRIPTION
**Pull request by karola312**
I want to merge this change because I want to always run critical tests

**PR intended to be tested with API branch:** 

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-4042 Always run critical tests in CI](https://app.clickup.com/t/2549495/SALEOR-4042)

**Comment by jwm0** [comment]
@karola312 can you create some sample PR that points to this branch (SALEOR-4042-Always-run-critical-tests) so we can test out the job? How stable are critical tests?

**Review by jwm0 — COMMENTED** [review]
See my comment above

**Comment by eCzerniak** [comment]
> @karola312 can you create some sample PR that points to this branch ([SALEOR-4042](https://app.clickup.com/t/2549495/SALEOR-4042)-Always-run-critical-tests) so we can test out the job? How stable are critical tests?

@karola312 ☝️

**Review by jwm0 — COMMENTED** [review]
Re-request me for review when tests pass

**Review by jwm0 — APPROVED** [review]

**Review by eCzerniak — APPROVED** [review]

**Pull request merged**
