### PR TITLE
Fix "problem" typo

### PR DESCRIPTION
**Pull request by wlcx**
Fix a very minor typo

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `data-test-id` are added for new elements
4. [ ] The changes are tested in Chrome/Firefox/Safari browsers and in light/dark mode
5. [ ] Your code works with the latest stable version of the core

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
APPS_MARKETPLACE_API_URI=https://apps.staging.saleor.io/api/v2/saleor-apps

### Do you want to run more stable tests?

To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=1

### CODE REVIEW

**Review by krzysztofzuraw — DISMISSED** [review]

**Comment by krzysztofzuraw** [comment]
@wclx can you resolve the conflict 🙏🏻

**Review by krzysztofzuraw — APPROVED** [review]

**Comment by krzysztofzuraw** [comment]
@wlcx I'm wondering if we need to have such large changes to fix the typo 🤔 Did you update translations to other langs by hand?

**Review by Droniu — APPROVED** [review]

**Comment by wlcx** [comment]
@krzysztofzuraw Yep - I couldn't see how the locale files were generated from `defaultMessages` (are they?) and the typo existed in them all so I just find/replaced the string "poblem".

**Comment by andrzejewsky** [comment]
hey, sorry for the waiting that long, could you please resolve the conflicts? I think once it's done we can merge it

**Pull request closed without merging**
