### PR TITLE
Add optional 'allow-popups' to app's iframe

### PR DESCRIPTION
**Pull request by Cloud11PL**
I want to merge this change because it allows for optional 'allow-popups' to be passed to iframe's sandbox.

Related PR: https://github.com/saleor/saleor-app-marketplace/pull/28

**PR intended to be tested with API branch:** 

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://marketplace-git-saleor-7182-marketplace-link-fix-saleorcommerce.vercel.app/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-7182 Frontend bug template](https://app.clickup.com/t/2549495/SALEOR-7182)

**Comment by Cloud11PL** [comment]
@jwm0 to allow opening links in new tab with "_blank". See here -> https://github.com/saleor/saleor-app-marketplace/pull/28/files

**Comment by jwm0** [comment]
> @jwm0 to allow opening links in new tab with "_blank". See here -> https://github.com/saleor/saleor-app-marketplace/pull/28/files

You can use app-bridge for that
https://github.com/saleor/app-bridge#available-actions

**Comment by jwm0** [comment]
@Cloud11PL yes, that would be a good idea. In this case we can take the small DX penalty if it results in a better security overall, we want all popups to be routed through dashboard.

**Comment by Cloud11PL** [comment]
@jwm0 Fixed here - https://github.com/saleor/saleor-app-marketplace/pull/28. Closing

**Pull request closed without merging**
