### PR TITLE
Expose marketplace in Dashboard builds

### PR DESCRIPTION
**Pull request by magul**
I want to merge this change because we want to expose Marketplace (AKA App templates) in Saleor dashboar beyond staging build of main branch.

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://marketplace-gray.vercel.app/

### CODE REVIEW

**Review by timuric — APPROVED** [review]
Why do we call it gray?

**Comment by magul** [comment]
@timuric it's generic name provided by Vercel. I recall we had a conversation about vanity domain for Marketplace (now App templates), but don't believe we have a ticket to actually deliver that.

As soon as we figure out, how we want to call it we can change it to e.g.: apps.saleor.io (we can even do that before merging this pull request).

**Review by NyanKiyoshi — APPROVED** [review]

**Comment by magul** [comment]
@timuric new domain is already set up, so I've changed it here, whenever you're ready we can merge that one and marketplace will be released.

**Review by andrzejewsky — APPROVED** [review]

**Comment by lkostrowski** [comment]
🎉 💯

**Pull request merged**
